;; for basic types (u256, byte, length) see common.bnf

;; all fields without _cmtmnt are non-lossy encodings of a pre-image into a finite field
;; logic_cmtmnt and value_cmtmnt are commitments to program-field-elements (see data-storage.bnf)
;; 224 bytes
resource ::= <logic-cmtmnt> <label> <quantity> <value-cmtmnt> <nonce> <nc> <ephemeral>

logic_cmtmnt ::= <finite-field-element>

label ::= <finite-field-element>

quantity ::= <finite-field-element>

value_cmtmnt ::= <finite-field-element>

nonce ::= <finite-field-element>

nc ::= <finite-field-element>

ephemeral ::= <finite-field-element>